package com.DeltaFish.mapper;

import com.DeltaFish.pojo.TUser;

import java.util.List;

import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Options;

public interface TUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Sat May 05 16:02:56 CST 2018
     */


    public int insertUser(TUser record);

    public TUser findUserById(String id) throws Exception;

    public int deleteUser(String id) throws Exception;

    List<TUser> selectAll();
}